// frontend/src/components/FormatConverter.tsx
import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Play, Pause, Download, CheckCircle, AlertCircle, FileType, ArrowRight } from 'lucide-react'
import { toast } from 'sonner'
import { Card, CardHeader, CardTitle, CardContent } from './ui/card'
import { Button } from './ui/button'
import { Progress } from './ui/progress'
import { FileUpload } from './FileUpload'
import { audioApi } from '../lib/api'

const SUPPORTED_FORMATS = [
  { value: 'mp3', label: 'MP3', description: 'Most compatible' },
  { value: 'wav', label: 'WAV', description: 'Uncompressed' },
  { value: 'flac', label: 'FLAC', description: 'Lossless compression' },
  { value: 'm4a', label: 'M4A', description: 'Apple format' },
  { value: 'ogg', label: 'OGG', description: 'Open source' }
]

export const FormatConverter: React.FC = () => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [targetFormat, setTargetFormat] = useState<string>('mp3')
  const [isProcessing, setIsProcessing] = useState(false)
  const [progress, setProgress] = useState(0)
  const [result, setResult] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const [audioElement, setAudioElement] = useState<HTMLAudioElement | null>(null)

  const handleFileSelect = (file: File) => {
    setSelectedFile(file)
    setResult(null)
    setError(null)
    setProgress(0)
    toast.success(`File selected: ${file.name}`)
  }

  const handleRemoveFile = () => {
    setSelectedFile(null)
    setResult(null)
    setError(null)
    setProgress(0)
  }

  useEffect(() => {
    if (isProcessing) {
      const interval = setInterval(() => {
        setProgress(prev => {
          if (prev >= 90) return prev
          return prev + Math.random() * 8
        })
      }, 400)
      return () => clearInterval(interval)
    }
  }, [isProcessing])

  const handleProcess = async () => {
    if (!selectedFile) return

    setIsProcessing(true)
    setError(null)
    setProgress(0)

    try {
      toast.loading(`Converting to ${targetFormat.toUpperCase()}...`, { id: 'processing' })
      const response = await audioApi.convertFormat(selectedFile, targetFormat)
      setProgress(100)
      setResult(response)
      toast.success('Conversion completed successfully!', { id: 'processing' })
    } catch (err: any) {
      const errorMsg = err.response?.data?.detail || 'Failed to convert audio file'
      setError(errorMsg)
      toast.error(errorMsg, { id: 'processing' })
    } finally {
      setIsProcessing(false)
    }
  }

  const togglePlayback = () => {
    if (audioElement) {
      if (isPlaying) {
        audioElement.pause()
      } else {
        audioElement.play()
      }
      setIsPlaying(!isPlaying)
    }
  }

  const currentFormat = selectedFile?.name.split('.').pop()?.toUpperCase() || ''

  return (
    <motion.div 
      className="space-y-6"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Controls */}
        <motion.div 
          className="lg:col-span-2 space-y-6"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <Card>
            <CardHeader className="pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-primary/10 rounded-lg">
                  <FileType className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <CardTitle className="text-xl">Format Converter</CardTitle>
                  <p className="text-sm text-muted-foreground mt-1">
                    Convert audio files between different formats with quality preservation
                  </p>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-6">
              <FileUpload 
                onFileSelect={handleFileSelect}
                onRemoveFile={handleRemoveFile}
                isProcessing={isProcessing}
                progress={progress}
                selectedFile={selectedFile}
              />
              
              <AnimatePresence>
                {selectedFile && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className="space-y-6"
                  >
                    {/* Format Selection */}
                    <div className="space-y-4">
                      <div className="flex items-center justify-center gap-4 p-4 bg-muted/30 rounded-lg">
                        <div className="text-center">
                          <div className="text-2xl font-bold text-primary">{currentFormat}</div>
                          <div className="text-xs text-muted-foreground">Current</div>
                        </div>
                        <ArrowRight className="h-6 w-6 text-muted-foreground" />
                        <div className="text-center">
                          <div className="text-2xl font-bold text-primary">{targetFormat.toUpperCase()}</div>
                          <div className="text-xs text-muted-foreground">Target</div>
                        </div>
                      </div>

                      <div className="space-y-3">
                        <label className="text-sm font-medium">Choose target format:</label>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                          {SUPPORTED_FORMATS.map((format) => (
                            <motion.button
                              key={format.value}
                              className={`p-3 rounded-lg border-2 transition-all ${
                                targetFormat === format.value
                                  ? 'border-primary bg-primary/10 text-primary'
                                  : 'border-muted bg-background hover:border-primary/50'
                              }`}
                              onClick={() => setTargetFormat(format.value)}
                              whileHover={{ scale: 1.02 }}
                              whileTap={{ scale: 0.98 }}
                            >
                              <div className="font-medium">{format.label}</div>
                              <div className="text-xs text-muted-foreground mt-1">
                                {format.description}
                              </div>
                            </motion.button>
                          ))}
                        </div>
                      </div>
                    </div>

                    <Button 
                      onClick={handleProcess}
                      disabled={!selectedFile || isProcessing}
                      className="w-full h-12 text-base font-medium"
                      size="lg"
                    >
                      {isProcessing ? (
                        <motion.div 
                          className="flex items-center gap-2"
                          animate={{ opacity: [1, 0.7, 1] }}
                          transition={{ duration: 1.5, repeat: Infinity }}
                        >
                          <FileType className="h-5 w-5" />
                          Converting... {Math.round(progress)}%
                        </motion.div>
                      ) : (
                        <>
                          <FileType className="h-5 w-5 mr-2" />
                          Convert to {targetFormat.toUpperCase()}
                        </>
                      )}
                    </Button>
                  </motion.div>
                )}
              </AnimatePresence>
            </CardContent>
          </Card>
        </motion.div>

        {/* Status & Results */}
        <motion.div 
          className="space-y-4"
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <AnimatePresence>
            {isProcessing && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
              >
                <Card className="border-blue-200 bg-blue-50/50">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-3 mb-3">
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                      >
                        <FileType className="h-5 w-5 text-blue-600" />
                      </motion.div>
                      <div>
                        <p className="font-medium text-blue-900">Converting Audio</p>
                        <p className="text-xs text-blue-700">Processing format conversion...</p>
                      </div>
                    </div>
                    <Progress value={progress} className="h-2" />
                    <p className="text-xs text-blue-600 mt-2 text-center">{Math.round(progress)}% complete</p>
                  </CardContent>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {error && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
              >
                <Card className="border-red-200 bg-red-50/50">
                  <CardContent className="p-4">
                    <div className="flex items-start gap-3">
                      <AlertCircle className="h-5 w-5 text-red-600 mt-0.5" />
                      <div>
                        <p className="font-medium text-red-900 mb-1">Conversion Failed</p>
                        <p className="text-sm text-red-700">{error}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {result && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
              >
                <Card className="border-green-200 bg-green-50/50">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-3 mb-4">
                      <CheckCircle className="h-5 w-5 text-green-600" />
                      <div>
                        <p className="font-medium text-green-900">Conversion Complete!</p>
                        <p className="text-sm text-green-700">{result.message}</p>
                      </div>
                    </div>
                    
                    {result.output_url && (
                      <div className="space-y-3">
                        <div className="p-3 bg-white/50 rounded-lg">
                          <audio 
                            ref={setAudioElement}
                            className="w-full"
                            onPlay={() => setIsPlaying(true)}
                            onPause={() => setIsPlaying(false)}
                            onEnded={() => setIsPlaying(false)}
                          >
                            <source src={result.output_url} type="audio/mpeg" />
                          </audio>
                        </div>
                        
                        <div className="flex gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={togglePlayback}
                            className="flex-1"
                          >
                            {isPlaying ? (
                              <><Pause className="h-4 w-4 mr-2" />Pause</>
                            ) : (
                              <><Play className="h-4 w-4 mr-2" />Play</>
                            )}
                          </Button>
                          <Button
                            size="sm"
                            asChild
                            className="flex-1"
                          >
                            <a href={result.output_url} download>
                              <Download className="h-4 w-4 mr-2" />
                              Download
                            </a>
                          </Button>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>

          <Card className="bg-muted/30">
            <CardContent className="p-4">
              <h3 className="font-medium mb-2 text-sm">Format Guide</h3>
              <ul className="text-xs text-muted-foreground space-y-1">
                <li>• MP3: Universal compatibility</li>
                <li>• WAV: Best quality, large files</li>
                <li>• FLAC: Lossless compression</li>
                <li>• M4A: Apple devices optimized</li>
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </motion.div>
  )
}

// frontend/pages/format-converter.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900">
    <!-- Header -->
    <header class="pt-8 pb-4">
      <div class="container mx-auto px-4">
        <div class="flex items-center justify-between">
          <NuxtLink to="/" class="text-white hover:text-purple-300 transition-colors">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
            </svg>
          </NuxtLink>
          <h1 class="text-3xl md:text-4xl font-bold text-white">
            Format <span class="gradient-text">Converter</span>
          </h1>
          <div class="w-6"></div>
        </div>
        <p class="text-center text-white opacity-70 mt-2">
          Convert between all major audio formats with customizable quality
        </p>
      </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto px-4 pb-16">
      <div class="max-w-2xl mx-auto">
        <!-- Upload Section -->
        <div class="glass-card p-8 mb-6">
          <h2 class="text-xl font-semibold text-white mb-6">Upload Audio File</h2>
          
          <Uploader
            v-model="selectedFile"
            :is-uploading="isProcessing"
            :upload-progress="progress"
            @file-selected="handleFileSelected"
          />
        </div>

        <!-- Format Selection -->
        <div v-if="selectedFile && !isProcessing" class="glass-card p-8 mb-6">
          <h3 class="text-xl font-semibold text-white mb-6">Convert To</h3>
          
          <!-- Current Format Info -->
          <div class="bg-white bg-opacity-10 rounded-lg p-4 mb-6">
            <p class="text-white font-medium mb-2">Current Format</p>
            <p class="text-white opacity-80">{{ getCurrentFormat() }}</p>
          </div>

          <!-- Format Options -->
          <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
            <div
              v-for="format in formats"
              :key="format.value"
              @click="selectedFormat = format.value"
              :class="[
                'p-4 rounded-lg border-2 cursor-pointer transition-all',
                selectedFormat === format.value
                  ? 'border-purple-400 bg-purple-500 bg-opacity-20'
                  : 'border-white border-opacity-20 bg-white bg-opacity-5 hover:border-opacity-40'
              ]"
            >
              <div class="text-center">
                <p class="text-white font-semibold">{{ format.label }}</p>
                <p class="text-white opacity-60 text-sm">{{ format.description }}</p>
              </div>
            </div>
          </div>

          <!-- Process Button -->
          <div class="text-center">
            <button
              @click="processAudio"
              :disabled="!selectedFormat || selectedFormat === getCurrentFormat()"
              class="btn-primary px-8 py-3 text-lg font-semibold disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Convert to {{ selectedFormat?.toUpperCase() || 'Format' }}
            </button>
            <p v-if="selectedFormat === getCurrentFormat()" class="text-white opacity-60 text-sm mt-2">
              File is already in {{ selectedFormat }} format
            </p>
          </div>
        </div>

        <!-- Processing Status -->
        <div v-if="isProcessing" class="glass-card p-8 mb-6">
          <div class="text-center">
            <div class="animate-spin inline-block w-8 h-8 border-4 border-white border-t-transparent rounded-full mb-4"></div>
            <p class="text-white text-lg font-medium">Converting audio...</p>
            <p class="text-white opacity-70">Converting to {{ selectedFormat?.toUpperCase() }}</p>
            <div v-if="progress > 0" class="mt-4">
              <div class="w-full bg-white bg-opacity-20 rounded-full h-2">
                <div 
                  class="progress-bar h-2"
                  :style="{ width: progress + '%' }"
                ></div>
              </div>
              <p class="text-sm text-white opacity-75 mt-2">{{ progress }}% complete</p>
            </div>
          </div>
        </div>

        <!-- Results Section -->
        <div v-if="result" class="glass-card p-8 mb-6">
          <h3 class="text-xl font-semibold text-white mb-4">✓ Conversion Complete</h3>
          
          <!-- Conversion Summary -->
          <div class="bg-white bg-opacity-10 rounded-lg p-4 mb-4">
            <p class="text-white font-medium mb-2">Conversion Details:</p>
            <div class="text-white opacity-80 text-sm space-y-1">
              <p>• Original: {{ getFileExtension(selectedFile.name).toUpperCase() }}</p>
              <p>• Converted to: {{ result.target_format?.toUpperCase() }}</p>
              <p>• Status: {{ result.message }}</p>
            </div>
          </div>
          
          <div class="space-y-4">
            <div class="flex items-center justify-between p-4 bg-white bg-opacity-10 rounded-lg">
              <div>
                <p class="text-white font-medium">Converted Audio</p>
                <p class="text-white opacity-70 text-sm">Ready for download</p>
              </div>
              <div class="flex space-x-2">
                <!-- Preview Button -->
                <button
                  @click="previewAudio"
                  class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h1m4 0h1m-6 4h1m4 0h1m5-6V8a4 4 0 00-8 0v2m7 4v1a1 1 0 01-1 1h-4a1 1 0 01-1-1v-1"></path>
                  </svg>
                </button>
                <!-- Download Button -->
                <a
                  :href="downloadUrl"
                  download
                  class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors inline-flex items-center"
                >
                  <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-4-4m4 4l4-4m-6 4h8"></path>
                  </svg>
                </a>
              </div>
            </div>

            <!-- Audio Preview -->
            <div v-if="showPreview" class="p-4 bg-white bg-opacity-10 rounded-lg">
              <p class="text-white font-medium mb-2">Audio Preview</p>
              <audio ref="audioPlayer" controls class="w-full">
                <source :src="downloadUrl" :type="'audio/' + result.target_format">
                Your browser does not support the audio element.
              </audio>
            </div>
          </div>

          <!-- Process Another File -->
          <div class="mt-6 text-center">
            <button
              @click="resetForm"
              class="text-white border border-white border-opacity-30 hover:border-opacity-50 px-6 py-2 rounded-lg transition-colors"
            >
              Convert Another File
            </button>
          </div>
        </div>

        <!-- Error Message -->
        <div v-if="errorMessage" class="glass-card p-6 border border-red-500 border-opacity-30 mb-6">
          <div class="flex items-center text-red-300">
            <svg class="h-6 w-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <div>
              <p class="font-medium">Conversion Failed</p>
              <p class="text-sm opacity-75">{{ errorMessage }}</p>
            </div>
          </div>
          <button
            @click="resetForm"
            class="mt-4 text-white border border-white border-opacity-30 hover:border-opacity-50 px-4 py-2 rounded-lg transition-colors text-sm"
          >
            Try Again
          </button>
        </div>

        <!-- Info Section -->
        <div class="glass-card p-6">
          <h3 class="text-lg font-semibold text-white mb-3">Format Information</h3>
          <ul class="text-white opacity-80 space-y-2 text-sm">
            <li>• <strong>MP3:</strong> Widely compatible, good compression</li>
            <li>• <strong>WAV:</strong> Uncompressed, highest quality</li>
            <li>• <strong>FLAC:</strong> Lossless compression, high quality</li>
            <li>• <strong>M4A:</strong> Good quality, Apple ecosystem friendly</li>
            <li>• <strong>OGG:</strong> Open source, good compression</li>
          </ul>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup>
// Meta tags
useHead({
  title: 'Audio Format Converter - ODOREMOVER',
  meta: [
    { name: 'description', content: 'Convert between all major audio formats with customizable quality.' }
  ]
})

// Composables
const { convertFormat, getDownloadUrl } = useApi()

// Reactive state
const selectedFile = ref(null)
const isProcessing = ref(false)
const progress = ref(0)
const result = ref(null)
const errorMessage = ref('')
const showPreview = ref(false)
const audioPlayer = ref(null)
const selectedFormat = ref('mp3')

// Format options
const formats = [
  { value: 'mp3', label: 'MP3', description: 'Universal' },
  { value: 'wav', label: 'WAV', description: 'Uncompressed' },
  { value: 'flac', label: 'FLAC', description: 'Lossless' },
  { value: 'm4a', label: 'M4A', description: 'Apple' },
  { value: 'ogg', label: 'OGG', description: 'Open Source' },
  { value: 'aac', label: 'AAC', description: 'Advanced' }
]

// Computed
const downloadUrl = computed(() => {
  if (!result.value) return ''
  const filename = result.value.output_file.replace('/download/', '')
  return getDownloadUrl(filename)
})

// Methods
const handleFileSelected = (file) => {
  selectedFile.value = file
  resetState()
  
  // Set default conversion format based on current format
  const currentFormat = getCurrentFormat()
  selectedFormat.value = currentFormat === 'mp3' ? 'wav' : 'mp3'
}

const getCurrentFormat = () => {
  if (!selectedFile.value) return ''
  return getFileExtension(selectedFile.value.name).toLowerCase().replace('.', '')
}

const processAudio = async () => {
  if (!selectedFile.value || !selectedFormat.value) return

  isProcessing.value = true
  progress.value = 0
  errorMessage.value = ''

  try {
    const response = await convertFormat(
      selectedFile.value,
      selectedFormat.value,
      (progressValue) => {
        progress.value = progressValue
      }
    )

    if (response.success) {
      result.value = response
    } else {
      throw new Error(response.error || 'Conversion failed')
    }
  } catch (error) {
    console.error('Format conversion error:', error)
    errorMessage.value = error.response?.data?.error || error.message || 'An error occurred during conversion'
  } finally {
    isProcessing.value = false
    progress.value = 0
  }
}

const previewAudio = () => {
  showPreview.value = !showPreview.value
  if (showPreview.value && audioPlayer.value) {
    nextTick(() => {
      audioPlayer.value.load()
    })
  }
}

const resetForm = () => {
  selectedFile.value = null
  selectedFormat.value = 'mp3'
  resetState()
}

const resetState = () => {
  result.value = null
  errorMessage.value = ''
  isProcessing.value = false
  progress.value = 0
  showPreview.value = false
}

const getFileExtension = (filename) => {
  return filename.slice(filename.lastIndexOf('.'))
}
</script>
