// frontend/pages/tools/index.jsx
import Head from 'next/head'
import Header from '../../components/Header'
import ToolCard from '../../components/ToolCard'
import { 
  Mic, 
  Music, 
  RefreshCw, 
  Scissors, 
  ShieldCheck, 
  Volume2,
  Wand2,
  Edit3,
  RotateCcw,
  Sliders
} from 'lucide-react'

export default function Tools() {
  const tools = [
    {
      title: "Vocal Remover",
      description: "Remove vocals from songs to create instrumental tracks or karaoke versions using AI-powered separation.",
      href: "/tools/vocal-remover",
      icon: Mic,
      gradient: "from-red-500 to-pink-600"
    },
    {
      title: "Pitch & Tempo",
      description: "Adjust pitch and tempo independently for creative effects and music production.",
      href: "/tools/pitch-tempo",
      icon: Music,
      gradient: "from-blue-500 to-cyan-600"
    },
    {
      title: "Format Converter",
      description: "Convert audio files between different formats (MP3, WAV, FLAC, etc.) with quality options.",
      href: "/tools/converter",
      icon: RefreshCw,
      gradient: "from-green-500 to-emerald-600"
    },
    {
      title: "Audio Editor",
      description: "Cut, trim, and join audio files with precision timing controls.",
      href: "/tools/cutter-joiner",
      icon: Scissors,
      gradient: "from-purple-500 to-indigo-600"
    },
    {
      title: "Noise Reducer",
      description: "Remove background noise and improve audio quality using advanced algorithms.",
      href: "/tools/noise-reducer",
      icon: ShieldCheck,
      gradient: "from-yellow-500 to-orange-600"
    },
    {
      title: "Volume Normalizer",
      description: "Enhance audio volume with professional normalization and gain control.",
      href: "/tools/volume-normalizer",
      icon: Volume2,
      gradient: "from-pink-500 to-rose-600"
    },
    {
      title: "Fade Effects",
      description: "Add professional fade in/out effects to create smooth audio transitions.",
      href: "/tools/fade-effect",
      icon: Wand2,
      gradient: "from-violet-500 to-purple-600"
    },
    {
      title: "Metadata Editor",
      description: "Edit MP3 tags including title, artist, album, and year information.",
      href: "/tools/metadata-editor",
      icon: Edit3,
      gradient: "from-indigo-500 to-blue-600"
    },
    {
      title: "Audio Reverser",
      description: "Reverse audio playback completely for special effects and creative projects.",
      href: "/tools/audio-reverse",
      icon: RotateCcw,
      gradient: "from-cyan-500 to-teal-600"
    },
    {
      title: "3-Band EQ",
      description: "Adjust low, mid, and high frequencies with professional equalizer presets.",
      href: "/tools/equalizer",
      icon: Sliders,
      gradient: "from-emerald-500 to-green-600"
    }
  ]

  return (
    <>
      <Head>
        <title>Audio Processing Tools - ODOREMOVER Audio Suite</title>
        <meta name="description" content="Complete collection of professional audio processing tools. Remove vocals, adjust pitch, convert formats, and enhance your audio." />
      </Head>

      <div className="min-h-screen">
        <Header />

        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          {/* Header */}
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Audio Processing Tools
            </h1>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              Professional-grade audio tools for all your processing needs. 
              Choose from our comprehensive collection of features designed for creators, 
              musicians, and audio professionals.
            </p>
          </div>

          {/* Tools Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {tools.map((tool, index) => (
              <ToolCard
                key={index}
                title={tool.title}
                description={tool.description}
                href={tool.href}
                icon={tool.icon}
                gradient={tool.gradient}
              />
            ))}
          </div>

          {/* Help Section */}
          <div className="mt-20 text-center">
            <div className="glass-card max-w-2xl mx-auto">
              <h2 className="text-2xl font-bold text-white mb-4">
                Need Help Getting Started?
              </h2>
              <p className="text-gray-300 mb-6">
                Each tool is designed to be intuitive and powerful. Simply upload your audio file, 
                adjust the settings to your preference, and download the processed result.
              </p>
              <div className="space-y-2 text-sm text-gray-400">
                <p>✓ Supports all major audio formats</p>
                <p>✓ Professional-quality processing</p>
                <p>✓ Fast and secure file handling</p>
                <p>✓ No registration required</p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}

// frontend/pages/tools.vue
<template>
  <div class="py-16 px-4">
    <div class="max-w-6xl mx-auto">
      <div class="text-center mb-16">
        <h1 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
          Audio Processing Tools
        </h1>
        <p class="text-xl text-gray-600 max-w-2xl mx-auto">
          Professional-grade audio tools designed for creators, musicians, and audio enthusiasts.
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <!-- Vocal Remover -->
        <NuxtLink to="/vocal-remover" class="card p-6 hover:shadow-lg transition-all group">
          <div class="flex items-center mb-4">
            <div class="p-3 bg-blue-100 rounded-lg group-hover:bg-blue-200 transition-colors">
              <svg class="h-8 w-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 ml-4">Vocal Remover</h3>
          </div>
          <p class="text-gray-600 mb-4">
            Remove vocals from any audio track using AI-powered center channel extraction. Perfect for creating karaoke tracks.
          </p>
          <span class="text-blue-600 font-medium group-hover:text-blue-700">
            Use Tool →
          </span>
        </NuxtLink>

        <!-- Pitch & Tempo -->
        <NuxtLink to="/pitch-shifter" class="card p-6 hover:shadow-lg transition-all group">
          <div class="flex items-center mb-4">
            <div class="p-3 bg-green-100 rounded-lg group-hover:bg-green-200 transition-colors">
              <svg class="h-8 w-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 ml-4">Pitch & Tempo</h3>
          </div>
          <p class="text-gray-600 mb-4">
            Adjust pitch and tempo independently with high-quality algorithms. Change key without affecting speed.
          </p>
          <span class="text-blue-600 font-medium group-hover:text-blue-700">
            Use Tool →
          </span>
        </NuxtLink>

        <!-- Format Converter -->
        <NuxtLink to="/format-converter" class="card p-6 hover:shadow-lg transition-all group">
          <div class="flex items-center mb-4">
            <div class="p-3 bg-purple-100 rounded-lg group-hover:bg-purple-200 transition-colors">
              <svg class="h-8 w-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 9l4-4 4 4m0 6l-4 4-4-4"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 ml-4">Format Converter</h3>
          </div>
          <p class="text-gray-600 mb-4">
            Convert between all major audio formats including MP3, WAV, FLAC, and more with customizable quality settings.
          </p>
          <span class="text-blue-600 font-medium group-hover:text-blue-700">
            Use Tool →
          </span>
        </NuxtLink>

        <!-- Audio Editor -->
        <NuxtLink to="/audio-editor" class="card p-6 hover:shadow-lg transition-all group">
          <div class="flex items-center mb-4">
            <div class="p-3 bg-orange-100 rounded-lg group-hover:bg-orange-200 transition-colors">
              <svg class="h-8 w-8 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 ml-4">Audio Editor</h3>
          </div>
          <p class="text-gray-600 mb-4">
            Cut, trim, and join audio files with precision timing controls. Professional editing made simple.
          </p>
          <span class="text-blue-600 font-medium group-hover:text-blue-700">
            Use Tool →
          </span>
        </NuxtLink>

        <!-- Noise Reducer -->
        <NuxtLink to="/noise-reducer" class="card p-6 hover:shadow-lg transition-all group">
          <div class="flex items-center mb-4">
            <div class="p-3 bg-red-100 rounded-lg group-hover:bg-red-200 transition-colors">
              <svg class="h-8 w-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 ml-4">Noise Reducer</h3>
          </div>
          <p class="text-gray-600 mb-4">
            Remove background noise and improve audio clarity using advanced AI algorithms. Clean up your recordings.
          </p>
          <span class="text-blue-600 font-medium group-hover:text-blue-700">
            Use Tool →
          </span>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup>
useHead({
  title: 'Audio Processing Tools - ODOREMOVER',
  meta: [
    { name: 'description', content: 'Complete suite of professional audio processing tools including vocal removal, pitch shifting, format conversion, and more.' }
  ]
})
</script>
